site_name: Phoad
site_description: App for memorizing your photos at specific locations
repo_url: https://github.com/faderskd/Phoad-server
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/faderskd">faderskd</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
